### PR TITLE
zigify the repo

### PR DESCRIPTION
**Pull request by wizardofzos**
If you'd merge this with master, I could use your repo for the demo at GSE-UK conf.
Otherwise I'd just use my forked copy ;)

Cheers!

### CODE REVIEW

**Comment by wizardofzos** [comment]
Would be nice if you'd squash this into one commit :)

**Comment by davidegirardi** [comment]
Can't wait to try zigi myself!

**Comment by wizardofzos** [comment]
Won't be long :)

**Comment by wizardofzos** [comment]
Thanks for merging the stuff in.......this way this repo 'works' with zigi without being created with zigi

**Pull request merged**
